### ISSUE TITLE
Getting 'DATABASE_URL' is not recognized as an internal or external command on running make run-api-node command

### ISSUE THREAD

**Issue by ankitr21** [sidpalas/devops-directive-docker-course#9]
PS D:\dockerCourse\devops-directive-docker-course\05-example-web-application\api-node> cd ..
PS D:\dockerCourse\devops-directive-docker-course\05-example-web-application> make run-api-node
Starting node api
cd api-node && \
                DATABASE_URL=postgres://postgres:foobarbaz@localhost:5432/postgres \
                npm run dev
'DATABASE_URL' is not recognized as an internal or external command,
operable program or batch file.
make: *** [run-api-node] Error 1

**Comment by rhengles** [comment]
It looks like you're trying to run on Windows, but this command syntax is from linux

**Comment by ankitr21** [comment]
Hi @rhengles can you please elaborate. which commands I need to map from linux to windows (powershell).

**Comment by rhengles** [comment]
If you can't research how to do that on your own, you're going to face much bigger problems after that. That is quite a basic thing to ask chatgpt, for example.

**Comment by ankitr21** [comment]
Got my mistake. Thank you @rhengles for pointing out that command syntax.
